### ISSUE TITLE
How...did you get banned on forums??

### ISSUE THREAD

**Issue by minijaham** [GodWeedZao/AutoClearChat#2]

**Comment by minijaham** [comment]
I already miss you m8

**Comment by GodWeedZao** [comment]
Hello, idk why but ik because dylan (dkktops) is stupid human he banned me because 1 typo (typo were F) in my post and im now not working in forum :L
so you can connect me is discord:
GᴏᴅWᴇᴇᴅZᴀᴏ#1558

**Comment by minijaham** [comment]
Ok lol
